### ISSUE TITLE
client.auth for redis doesn't occur

### ISSUE THREAD

**Issue by phwd** [e14n/databank-redis#4]
I think I've went through this driver up and down. auth() just isn't there. 
Maybe some sort of inclusion after 

    client = redis.createClient(port, host);

Then checking whether auth was given in the params list (only reasonable place to put it)

    if(auth_pass) {
        client.auth(auth_pass);
    }

Not sure what handlers you will want to check for here.

**Comment by debuos512** [comment]
Fixed in #6
